name: coverage

on:
  push:
  workflow_dispatch:
  pull_request:
    branches:
      - master

jobs:
    coverage:
        runs-on: ubuntu-latest
        steps:
          - name: Get Cover
            uses: orgoro/coverage@v3
            with:
                coverageFile: path/to/coverage.xml
                token: ${{ secrets.GITHUB_TOKEN }}